name: Update-toc

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Update TOC Interface version
        uses: p3lim/toc-interface-updater@v1

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update Interface version
          body:
          commit-message: Update Interface version
          branch: interface-version
          delete-branch: true

    env:
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
